version: "3"
services:
    fcc-node-app:
        build: .
        environment: 
            - PORT=3000
        depends_on: 
            - fcc-mongo-db
    fcc-mongo-db:
        image: mongo
        volumes:
            - mongo-db:/data/db
    fcc-redis-db:
        image: redis
    fcc-nginx:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
    mongo-db: